# Generated by Django 6.0.4 on 2026-04-28 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('libelle', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('ferie', 'Jour férié'), ('pont', 'Pont')], default='ferie', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'jour férié / pont',
                'ordering': ['jour'],
            },
        ),
        migrations.CreateModel(
            name='JourFerieRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_ferie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.jourferie')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.region')),
            ],
            options={
                'unique_together': {('jour_ferie', 'region')},
            },
        ),
        migrations.AddField(
            model_name='jourferie',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Laisser vide pour appliquer à toutes les régions.', through='calendar_app.JourFerieRegion', to='teams.region'),
        ),
    ]
