# Generated by Django 6.0.4 on 2026-04-28 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('couleur_hex', models.CharField(default='#CCCCCC', max_length=7)),
                ('visible_collaborateur', models.BooleanField(default=True, help_text='Si coché, un collaborateur peut saisir ce motif lui-même.')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'motif',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='PlanningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('demi_journee', models.CharField(choices=[('AM', 'Matin'), ('PM', 'Après-midi')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_entries', to='teams.collaborateur')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_created', to=settings.AUTH_USER_MODEL)),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='planning.motif')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrée planning',
                'ordering': ['jour', 'demi_journee', 'collaborateur'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('demi_journee', models.CharField(choices=[('AM', 'Matin'), ('PM', 'Après-midi')], max_length=2)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression')], max_length=10)),
                ('date_modif', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_effectuees', to=settings.AUTH_USER_MODEL)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_modifications', to='teams.collaborateur')),
                ('ancien_motif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_ancien', to='planning.motif')),
                ('nouveau_motif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_nouveau', to='planning.motif')),
                ('planning_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='planning.planningentry')),
            ],
            options={
                'verbose_name': 'historique modification',
                'ordering': ['-date_modif'],
            },
        ),
        migrations.AddIndex(
            model_name='planningentry',
            index=models.Index(fields=['collaborateur', 'jour'], name='idx_planning_collab_jour'),
        ),
        migrations.AddIndex(
            model_name='planningentry',
            index=models.Index(fields=['jour', 'motif'], name='idx_planning_jour_motif'),
        ),
        migrations.AddConstraint(
            model_name='planningentry',
            constraint=models.UniqueConstraint(fields=('collaborateur', 'jour', 'demi_journee'), name='planning_entry_unique_slot'),
        ),
        migrations.AddIndex(
            model_name='historiquemodification',
            index=models.Index(fields=['collaborateur', 'date_modif'], name='idx_historique_collab_date'),
        ),
    ]
