# Generated by Django 6.0.4 on 2026-04-28 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('automobile', 'Automobile'), ('construction', 'Construction'), ('rc', 'Responsabilité Civile'), ('dommages', 'Dommages'), ('immeuble', 'Immeuble')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'domaine',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'région',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='teams.domaine')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='teams.region')),
            ],
            options={
                'verbose_name': 'équipe',
                'ordering': ['region', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborateur', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collaborateurs', to='teams.equipe')),
            ],
            options={
                'verbose_name': 'collaborateur',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='AffectationCollaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='teams.collaborateur')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='teams.equipe')),
            ],
            options={
                'verbose_name': 'affectation collaborateur',
                'ordering': ['collaborateur', '-date_debut'],
            },
        ),
        migrations.AddIndex(
            model_name='collaborateur',
            index=models.Index(fields=['equipe', 'actif'], name='idx_collab_equipe_actif'),
        ),
        migrations.AddIndex(
            model_name='collaborateur',
            index=models.Index(fields=['user'], name='idx_collab_user'),
        ),
        migrations.AddConstraint(
            model_name='collaborateur',
            constraint=models.CheckConstraint(condition=models.Q(('date_sortie__isnull', True), ('date_sortie__gt', models.F('date_entree')), _connector='OR'), name='collaborateur_dates_coherentes'),
        ),
        migrations.AddIndex(
            model_name='affectationcollaborateur',
            index=models.Index(fields=['collaborateur', 'date_debut'], name='idx_affectation_collab_debut'),
        ),
        migrations.AddConstraint(
            model_name='affectationcollaborateur',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gt', models.F('date_debut')), _connector='OR'), name='affectation_dates_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='affectationcollaborateur',
            constraint=models.UniqueConstraint(condition=models.Q(('date_fin__isnull', True)), fields=('collaborateur',), name='affectation_unique_courante'),
        ),
        migrations.AddIndex(
            model_name='equipe',
            index=models.Index(fields=['region', 'active'], name='idx_equipe_region_active'),
        ),
        migrations.AddConstraint(
            model_name='equipe',
            constraint=models.UniqueConstraint(fields=('nom', 'region', 'domaine'), name='equipe_unique_nom_region_domaine'),
        ),
    ]
